{"name": "test_login_invalid_credentials", "status": "passed", "description": "Проверка:неправильные логин или пароль возвращают ошибку \"Учетная запись не найдена\", статус 404", "start": 1722978993296, "stop": 1722978993471, "uuid": "18324159-9a23-4906-b179-9050699c9fb9", "historyId": "ec706951e0c7470079769d6d675d4cda", "testCaseId": "ec706951e0c7470079769d6d675d4cda", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "20572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}