{"name": "test_create_duplicate_courier_fail", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('courier_data', <FixtureRequest for <Function test_create_duplicate_courier_fail>>)", "trace": "file C:\\Users\\79270\\PycharmProjects\\Sprint_7\\tests\\test_create_courier.py, line 22\n      @allure.description('Проверка создания двух одинаковых курьеров: статус 409; в ответе \"Этот логин уже используется\"')\n      def test_create_duplicate_courier_fail(self, courier_data):\nE       fixture 'courier_data' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\79270\\PycharmProjects\\Sprint_7\\tests\\test_create_courier.py:22"}, "description": "Проверка создания двух одинаковых курьеров: статус 409; в ответе \"Этот логин уже используется\"", "start": 1722544184411, "stop": 1722544184411, "uuid": "9fb87e50-b60e-4ec5-a096-4981be48329b", "historyId": "23c66a1a87a569e76bf5bf5bfd67ee1a", "testCaseId": "23c66a1a87a569e76bf5bf5bfd67ee1a", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "17016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}