{"name": "test_login_invalid_credentials", "status": "passed", "description": "Проверка:неправильные логин или пароль возвращают ошибку \"Учетная запись не найдена\", статус 404", "start": 1722980033183, "stop": 1722980033371, "uuid": "101fe0a8-087b-4955-ad6c-8ee5edf058b2", "historyId": "ec706951e0c7470079769d6d675d4cda", "testCaseId": "ec706951e0c7470079769d6d675d4cda", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "20288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}